# configs/experiment_rag.yaml
name: xpipe_rag_free
pipeline: rag
logdir: output/xpipe

# Retrieval config
retriever:
  name: simple_overlap
  top_k: 3

# Prompt/token budgets (optional; safe defaults are used if omitted)
prompt:
  budget_tokens: 900         # total input tokens (before generation)
  ctx_per_doc_tokens: 300    # max tokens per retrieved doc
  
# Stage → model mapping (models.yaml provides handles)
llms:
  synthesize:
    model: hf/gpt2         # or hf/distilgpt2 | ollama/llama3.2:3b | ollama/qwen2.5:3b
    params:
      max_new_tokens: 160
      temperature: 0.1

# Dataset lives under datasets/
dataset:
  path: datasets/tbmp_2024/chunks.jsonl   # produced by scripts/build_tbmp_dataset.py

# Demo queries (kept in config)
queries:
  - id: q1
    text: "What is the role of a motion to compel in TTAB discovery?"
  - id: q2
    text: "When are sanctions appropriate relative to motions to compel?"

# Optional explicit output paths (else auto-named)
outputs:
  run_jsonl: ""
  metrics_csv: ""